//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab8.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lab8.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Абакан
        ///Азов
        ///Александров
        ///Алексин
        ///Альметьевск
        ///Анапа
        ///Ангарск
        ///Анжеро-Судженск
        ///Апатиты
        ///Арзамас
        ///Армавир
        ///Арсеньев
        ///Артем
        ///Архангельск
        ///Асбест
        ///Астрахань
        ///Ачинск
        ///Балаково
        ///Балахна
        ///Балашиха
        ///Балашов
        ///Барнаул
        ///Батайск
        ///Белгород
        ///Белебей
        ///Белово
        ///Белогорск (Амурская область)
        ///Белорецк
        ///Белореченск
        ///Бердск
        ///Березники
        ///Березовский (Свердловская область)
        ///Бийск
        ///Биробиджан
        ///Благовещенск (Амурская область)
        ///Бор
        ///Борисоглебск
        ///Боровичи
        ///Братск
        ///Брянск
        ///Бугульма
        ///Буденновск
        ///Бузулук
        ///Буйнакск
        ///Великие Луки
        ///Вел [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string Cities {
            get {
                return ResourceManager.GetString("Cities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Многоканальные телекоммуникационные системы
        ///Радиосвязь, радиовещание и телевидение
        ///Сети связи и системы коммутации
        ///Компьютерные сети
        ///Программирование в компьютерных системах
        ///Прикладная информатика
        ///Обеспечение информационной безопасности телекоммуникационных систем
        ///Обеспечение информационной безопасности автоматизированных систем
        ///Банковское дело
        ///Экономика и бухгалтерский учет
        ///Почтовая связь.
        /// </summary>
        public static string Tracks {
            get {
                return ResourceManager.GetString("Tracks", resourceCulture);
            }
        }
    }
}
